#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_WORLD11 30
#define ID_TEX_WORLD111 31
#define ID_TEX_BLACK_1 32


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1 
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_TURTLE	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_DECORATION 6

#define OBJECT_TYPE_HALF_SOLID_BLOCK 7
#define OBJECT_TYPE_BLOCKING 8
#define OBJECT_TYPE_MARIO_BLOCKER 10
#define OBJECT_TYPE_REDGOOMBA 15
#define OBJECT_TYPE_PIRANHA_PLANT 16
#define OBJECT_TYPE_BULLET 160

#define OBJECT_TYPE_PIPE_TELEPORT 9

#define OBJECT_TYPE_PORTAL	50



#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_HOLD_IDLE_RIGHT 11721
#define ID_SPRITE_MARIO_HOLD_IDLE_LEFT 11711
#define ID_SPRITE_MARIO_HOLD_WALK_RIGHT 11722
#define ID_SPRITE_MARIO_HOLD_WALK_LEFT 11712
#define ID_SPRITE_MARIO_HOLD_RUN_RIGHT 11723
#define ID_SPRITE_MARIO_HOLD_RUN_LEFT 11713

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#define ID_SPRITE_MARIO_RACCOON (ID_SPRITE_MARIO + 4000)
#define ID_SPRITE_MARIO_RACCOON_IDLE (ID_SPRITE_MARIO_RACCOON + 100)
#define ID_SPRITE_MARIO_RACCOON_IDLE_LEFT (ID_SPRITE_MARIO_RACCOON_IDLE + 10)
#define ID_SPRITE_MARIO_RACOOON_IDLE_RIGHT (ID_SPRITE_MARIO_RACCOON_IDLE + 20)

#define ID_SPRITE_MARIO_RACCOON_WALKING (ID_SPRITE_MARIO_RACCOON + 200)
#define ID_SPRITE_MARIO_RACCOON_WALKING_LEFT (ID_SPRITE_MARIO_RACCOON_WALKING + 10)
#define ID_SPRITE_MARIO_RACCOON_WALKING_RIGHT (ID_SPRITE_MARIO_RACCOON_WALKING + 20)
#define ID_SPRITE_MARIO_RACCOON_RUNNING (ID_SPRITE_MARIO_RACCOON + 300)
#define ID_SPRITE_MARIO_RACCOON_RUNNING_LEFT (ID_SPRITE_MARIO_RACCOON_RUNNING + 10)
#define ID_SPRITE_MARIO_RACCOON_RUNNING_RIGHT (ID_SPRITE_MARIO_RACCOON_RUNNING + 20)
#define ID_SPRITE_MARIO_RACCOON_JUMP_WALK (ID_SPRITE_MARIO_RACCOON + 400)
#define ID_SPRITE_MARIO_RACCOON_JUMP_WALK_LEFT (ID_SPRITE_MARIO_RACCOON_JUMP_WALK + 10)
#define ID_SPRITE_MARIO_RACCOON_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_RACCOON_JUMP_WALK + 20)
#define ID_SPRITE_MARIO_RACCOON_JUMP_RUNNING (ID_SPRITE_MARIO_RACCOON + 500)
#define ID_SPRITE_MARIO_RACCOON_JUMP_RUNNING_LEFT (ID_SPRITE_MARIO_RACCOON_JUMP_RUNNING + 10)
#define ID_SPRITE_MARIO_RACCOON_JUMP_RUNNING_RIGHT (ID_SPRITE_MARIO_RACCOON_JUMP_RUNNING + 20)

#define ID_SPRITE_MARIO_RACCOON_SIT (ID_SPRITE_MARIO_RACCOON + 600)
#define ID_SPRITE_MARIO_RACCOON_SIT_LEFT (ID_SPRITE_MARIO_RACCOON_SIT + 10)
#define ID_SPRITE_MARIO_RACCOON_SIT_RIGHT (ID_SPRITE_MARIO_RACCOON_SIT + 20)

#define ID_SPRITE_MARIO_RACCOON_BRACE (ID_SPRITE_MARIO_RACCOON + 700)
#define ID_SPRITE_MARIO_RACCOON_BRACE_LEFT (ID_SPRITE_MARIO_RACCOON_BRACE + 10)
#define ID_SPRITE_MARIO_RACCOON_BRACE_RIGHT (ID_SPRITE_MARIO_RACCOON_BRACE + 20)

#define ID_SPRITE_MARIO_RACCOON_TRANSFORM_1 (ID_SPRITE_MARIO_RACCOON + 800)
#define ID_SPRITE_MARIO_RACCOON_TRANSFORM_2 (ID_SPRITE_MARIO_RACCOON_TRANSFORM_1 + 10)
#define ID_SPRITE_MARIO_RACCOON_TRANSFORM_3 (ID_SPRITE_MARIO_RACCOON_TRANSFORM_1 + 20)

#define ID_SPRITE_MARIO_RACCOON_HOLD_IDLE_RIGHT 14921
#define ID_SPRITE_MARIO_RACCOON_HOLD_IDLE_LEFT 14911
#define ID_SPRITE_MARIO_RACCOON_HOLD_WALK_RIGHT 14922
#define ID_SPRITE_MARIO_RACCOON_HOLD_WALK_LEFT 14912
#define ID_SPRITE_MARIO_RACCOON_HOLD_RUN_RIGHT 14923
#define ID_SPRITE_MARIO_RACCOON_HOLD_RUN_LEFT 14913

#define ID_SPRITE_MARIO_RACCOON_ATTACK_1 14924
#define ID_SPRITE_MARIO_RACCOON_ATTACK_2 14925
#define ID_SPRITE_MARIO_RACCOON_ATTACK_3 14926
#define ID_SPRITE_MARIO_RACCOON_ATTACK_4 14927

#pragma endregion 

#define ID_SPRITE_BRICK_QUESTION_1 20000
#define ID_SPRITE_BRICK_QUESTION_2 20001
#define ID_SPRITE_BRICK_QUESTION_3 20002
#define ID_SPRITE_BRICK_QUESTION_4 20003

#define ID_SPRITE_BRICK_EMPTY    20004

#define ID_SPRITE_ITEM_POINT_100	20100
#define ID_SPRITE_ITEM_MUSHROOM_RED		200000 
#define ID_SPRITE_ITEM_LEAF		200001 


#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_TURTLE 5000000
#define ID_SPRITE_TURTLE_WALK_LEFT_1 5000000
#define ID_SPRITE_TURTLE_WALK_LEFT_2 5000001
#define ID_SPRITE_TURTLE_WALK_RIGHT_1 5000002
#define ID_SPRITE_TURTLE_WALK_RIGHT_2 5000003
#define ID_SPRITE_TURTLE_SHELL_1 5000004
#define ID_SPRITE_TURTLE_SHELL_2 5000005

#define ID_SPRITE_LAND1 50000
#define ID_SPRITE_LAND1_BEGIN (ID_SPRITE_LAND1+1000)
#define ID_SPRITE_LAND1_MIDDLE (ID_SPRITE_LAND1+2000)
#define ID_SPRITE_LAND1_END (ID_SPRITE_LAND1+3000)

#define ID_SPRITE_RED_GOOMBA_WING_1   31101
#define ID_SPRITE_RED_GOOMBA_WING_2   31102
#define ID_SPRITE_RED_GOOMBA_WING_3   31103
#define ID_SPRITE_RED_GOOMBA_WING_4   31104

#define ID_SPRITE_RED_GOOMBA_WALK_1   31201
#define ID_SPRITE_RED_GOOMBA_WALK_2   31202

#define ID_SPRITE_RED_GOOMBA_DIE      31301



