#pragma once
#include "GameObject.h"
#include "Mario.h"

#define MARIO_LEVEL_RACCOON 3

#define ID_ANI_MARIO_RACCOON_IDLE_RIGHT   2000
#define ID_ANI_MARIO_RACCOON_IDLE_LEFT    2001
#define ID_ANI_MARIO_RACCOON_WALKING_RIGHT 2002
#define ID_ANI_MARIO_RACCOON_WALKING_LEFT  2003
#define ID_ANI_MARIO_RACCOON_RUNNING_RIGHT 2004
#define ID_ANI_MARIO_RACCOON_RUNNING_LEFT  2005
#define ID_ANI_MARIO_RACCOON_JUMP_WALK_RIGHT 2006
#define ID_ANI_MARIO_RACCOON_JUMP_WALK_LEFT  2007
#define ID_ANI_MARIO_RACCOON_JUMP_RUN_RIGHT  2008
#define ID_ANI_MARIO_RACCOON_JUMP_RUN_LEFT   2009
#define ID_ANI_MARIO_RACCOON_SIT_RIGHT 2010
#define ID_ANI_MARIO_RACCOON_SIT_LEFT  2011
#define ID_ANI_MARIO_RACCOON_BRACE_RIGHT 2012
#define ID_ANI_MARIO_RACCOON_BRACE_LEFT  2013


#define MARIO_RACCOON_BBOX_WIDTH  22
#define MARIO_RACCOON_BBOX_HEIGHT 26
#define MARIO_RACCOON_SITTING_BBOX_HEIGHT 17
#define MARIO_RACCOON_SIT_HEIGHT_ADJUST ((MARIO_RACCOON_BBOX_HEIGHT - MARIO_RACCOON_SITTING_BBOX_HEIGHT) / 2)

class CMarioRaccoon : public CMario {
public:
	CMarioRaccoon(float x, float y);
	void Render() override;

protected:
	int GetAniIdRaccoon();
	void GetBoundingBox(float& left, float& top, float& right, float& bottom);
	void SetState(int state) override;
};